CREATE TABLE data421(
   id      VARCHAR(2) NOT NULL PRIMARY KEY
  ,label   VARCHAR(17)
  ,type    VARCHAR(7) NOT NULL
  ,pattern VARCHAR(13)
);
INSERT INTO data421(id,label,type,pattern) VALUES ('A','학사정보','number','General');
INSERT INTO data421(id,label,type,pattern) VALUES ('B','재학','number','#,##0');
INSERT INTO data421(id,label,type,pattern) VALUES ('C','휴학','string',NULL);
INSERT INTO data421(id,label,type,pattern) VALUES ('D','블랙홀','string',NULL);
INSERT INTO data421(id,label,type,pattern) VALUES ('E','학업중단','string',NULL);
INSERT INTO data421(id,label,type,pattern) VALUES ('F','총원','date','yyyy. M. d');
INSERT INTO data421(id,label,type,pattern) VALUES ('G','Common Core','string',NULL);
INSERT INTO data421(id,label,type,pattern) VALUES ('H','OC(Out Circle)','string',NULL);
INSERT INTO data421(id,label,type,pattern) VALUES ('I','Total','number','#,##0');
INSERT INTO data421(id,label,type,pattern) VALUES ('J','개인정보관리','string',NULL);
INSERT INTO data421(id,label,type,pattern) VALUES ('K',NULL,'string',NULL);
INSERT INTO data421(id,label,type,pattern) VALUES ('L',NULL,'date','yyyymmdd');
INSERT INTO data421(id,label,type,pattern) VALUES ('M',NULL,'number','General');
INSERT INTO data421(id,label,type,pattern) VALUES ('N','학적관리 과정진행여부','date','yyyy. M. d');
INSERT INTO data421(id,label,type,pattern) VALUES ('O',NULL,'string',NULL);
INSERT INTO data421(id,label,type,pattern) VALUES ('P',NULL,'string',NULL);
INSERT INTO data421(id,label,type,pattern) VALUES ('Q','휴학','string',NULL);
INSERT INTO data421(id,label,type,pattern) VALUES ('R',NULL,'string',NULL);
INSERT INTO data421(id,label,type,pattern) VALUES ('S',NULL,'date','yyyy. M. d');
INSERT INTO data421(id,label,type,pattern) VALUES ('T',NULL,'string',NULL);
INSERT INTO data421(id,label,type,pattern) VALUES ('U','블랙홀','string',NULL);
INSERT INTO data421(id,label,type,pattern) VALUES ('V',NULL,'date','yyyy. M. d');
INSERT INTO data421(id,label,type,pattern) VALUES ('W',NULL,'string',NULL);
INSERT INTO data421(id,label,type,pattern) VALUES ('X','과정중단','string',NULL);
INSERT INTO data421(id,label,type,pattern) VALUES ('Y',NULL,'string',NULL);
INSERT INTO data421(id,label,type,pattern) VALUES ('Z','학습데이터','number','General');
INSERT INTO data421(id,label,type,pattern) VALUES ('AA',NULL,'number','General');
INSERT INTO data421(id,label,type,pattern) VALUES ('AB',NULL,'number','General');
INSERT INTO data421(id,label,type,pattern) VALUES ('AC',NULL,'string',NULL);
INSERT INTO data421(id,label,type,pattern) VALUES ('AD',NULL,'string',NULL);
INSERT INTO data421(id,label,type,pattern) VALUES ('AE','기타정보','string',NULL);
INSERT INTO data421(id,label,type,pattern) VALUES ('AF',NULL,'string',NULL);
INSERT INTO data421(id,label,type,pattern) VALUES ('AG',NULL,'string',NULL);
INSERT INTO data421(id,label,type,pattern) VALUES ('AH',NULL,'string',NULL);
INSERT INTO data421(id,label,type,pattern) VALUES ('AI',NULL,'string',NULL);
INSERT INTO data421(id,label,type,pattern) VALUES ('AJ',NULL,'string',NULL);
INSERT INTO data421(id,label,type,pattern) VALUES ('AK','라피신정보 관리 라피신 참여이력','string',NULL);
INSERT INTO data421(id,label,type,pattern) VALUES ('AL',NULL,'string',NULL);
INSERT INTO data421(id,label,type,pattern) VALUES ('AM',NULL,'number','General');
INSERT INTO data421(id,label,type,pattern) VALUES ('AN',NULL,'string',NULL);
INSERT INTO data421(id,label,type,pattern) VALUES ('AO','취창업지원관리 취창업지원관리','boolean',NULL);
INSERT INTO data421(id,label,type,pattern) VALUES ('AP',NULL,'date','yyyy. M. d');
INSERT INTO data421(id,label,type,pattern) VALUES ('AQ',NULL,'string',NULL);
INSERT INTO data421(id,label,type,pattern) VALUES ('AR','HRD-Net 활용','string',NULL);
INSERT INTO data421(id,label,type,pattern) VALUES ('AS',NULL,'string',NULL);
INSERT INTO data421(id,label,type,pattern) VALUES ('AT',NULL,'string',NULL);
INSERT INTO data421(id,label,type,pattern) VALUES ('AU',NULL,'string',NULL);
INSERT INTO data421(id,label,type,pattern) VALUES ('AV','기타 취업현황','date','yyyy. M. d');
INSERT INTO data421(id,label,type,pattern) VALUES ('AW',NULL,'string',NULL);
INSERT INTO data421(id,label,type,pattern) VALUES ('AX','인턴현황','string',NULL);
INSERT INTO data421(id,label,type,pattern) VALUES ('AY',NULL,'string',NULL);
INSERT INTO data421(id,label,type,pattern) VALUES ('AZ',NULL,'string',NULL);
INSERT INTO data421(id,label,type,pattern) VALUES ('BA',NULL,'string',NULL);
INSERT INTO data421(id,label,type,pattern) VALUES ('BB',NULL,'string',NULL);
INSERT INTO data421(id,label,type,pattern) VALUES ('BC',NULL,'string',NULL);
INSERT INTO data421(id,label,type,pattern) VALUES ('BD',NULL,'string',NULL);
INSERT INTO data421(id,label,type,pattern) VALUES ('BE','교육지원금 관리','number','General');
INSERT INTO data421(id,label,type,pattern) VALUES ('BF',NULL,'number','General');
INSERT INTO data421(id,label,type,pattern) VALUES ('BG',NULL,'string',NULL);
INSERT INTO data421(id,label,type,pattern) VALUES ('BH',NULL,'string',NULL);
INSERT INTO data421(id,label,type,pattern) VALUES ('BI',NULL,'string',NULL);
INSERT INTO data421(id,label,type,pattern) VALUES ('BJ',NULL,'string',NULL);
INSERT INTO data421(id,label,type,pattern) VALUES ('BK',NULL,'string',NULL);
INSERT INTO data421(id,label,type,pattern) VALUES ('BL',NULL,'number','#,##0;(#,##0)');
INSERT INTO data421(id,label,type,pattern) VALUES ('BM','출입카드정보','string',NULL);
INSERT INTO data421(id,label,type,pattern) VALUES ('BN',NULL,'string',NULL);
INSERT INTO data421(id,label,type,pattern) VALUES ('BO',NULL,'string',NULL);
INSERT INTO data421(id,label,type,pattern) VALUES ('BP',NULL,'string',NULL);
INSERT INTO data421(id,label,type,pattern) VALUES ('BQ',NULL,'string',NULL);
INSERT INTO data421(id,label,type,pattern) VALUES ('BR',NULL,'string',NULL);